name: pull_and_bear_replica
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  retrofit: ^4.0.1
  retrofit_generator: ^5.0.0
  analyzer: ^5.2.0
  dio: ^5.0.1
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^0.5.5
  device_info: ^2.0.3
  freezed: ^2.3.2
  get_it: ^7.2.0
  lottie: ^2.2.0
  country_code_picker: ^3.0.0
  image_picker: ^0.7.2+1
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  flutter_phoenix: ^1.1.0
  easy_localization: ^1.3.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  

